# Generated by Django 4.2.1 on 2023-06-08 02:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2023, 6, 7, 21, 35, 16, 588778)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2023, 6, 7, 21, 35, 16, 588778)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2023, 6, 7, 21, 35, 16, 587778)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ally',
            name='race',
            field=models.CharField(choices=[('DB', 'Dragonborn'), ('DW', 'Dwarf'), ('EF', 'Elf'), ('GN', 'Gnome'), ('HE', 'Half-Elf'), ('HF', 'Halfling'), ('HO', 'Half-Orc'), ('HU', 'Human'), ('TF', 'Tiefling'), ('CH', 'Changling'), ('CL', 'Colossus')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='race',
            field=models.CharField(choices=[('DB', 'Dragonborn'), ('DW', 'Dwarf'), ('EF', 'Elf'), ('GN', 'Gnome'), ('HE', 'Half-Elf'), ('HF', 'Halfling'), ('HO', 'Half-Orc'), ('HU', 'Human'), ('TF', 'Tiefling'), ('CH', 'Changling'), ('CL', 'Colossus')], max_length=30),
        ),
    ]
