# Generated by Django 4.2.1 on 2023-06-13 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0002_ally_date_modified_creature_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a class ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a race/species', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ally',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ally',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enemy',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 13, 17, 47, 33, 730898)),
        ),
        migrations.RemoveField(
            model_name='ally',
            name='race',
        ),
        migrations.AlterField(
            model_name='creature',
            name='damageType',
            field=models.CharField(blank=True, choices=[('AC', 'Acid'), ('BG', 'Bludgeoning'), ('CD', 'Cold'), ('FR', 'Fire'), ('FO', 'Force'), ('LG', 'Lightning'), ('NE', 'Necrotic'), ('PI', 'Piercing'), ('PY', 'Psychic'), ('RA', 'Radiant'), ('SL', 'Slashing'), ('TH', 'Thundering'), ('PO', 'Poison')], max_length=30),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 13, 17, 47, 33, 731895)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 13, 17, 47, 33, 729899)),
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='race',
        ),
        migrations.AddField(
            model_name='ally',
            name='charClass',
            field=models.ManyToManyField(blank='True', help_text='Enter a class for this character or leave blank if it is not known', to='dnd_codex.charclass'),
        ),
        migrations.AddField(
            model_name='creature',
            name='charClass',
            field=models.ManyToManyField(blank='True', help_text='Enter a class for this character or leave blank if it is not known', to='dnd_codex.charclass'),
        ),
        migrations.AddField(
            model_name='creature',
            name='race',
            field=models.ManyToManyField(help_text='Select a race from previous races or create a new one using the + button\n', to='dnd_codex.race'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='charClass',
            field=models.ManyToManyField(blank='True', help_text='Enter a class for this character or leave blank if it is not known', to='dnd_codex.charclass'),
        ),
        migrations.AddField(
            model_name='ally',
            name='race',
            field=models.ManyToManyField(help_text='Select a race from previous races or create a new one using the + button\n', to='dnd_codex.race'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='race',
            field=models.ManyToManyField(help_text='Select a race from previous races or create a new one using the + button\n', to='dnd_codex.race'),
        ),
    ]
