# Generated by Django 4.2.1 on 2023-06-15 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0015_damagetype_instance_count_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayableClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a class ', max_length=50)),
                ('instance_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ally',
            name='characterClass',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='characterClass',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='characterClass',
        ),
        migrations.AddField(
            model_name='race',
            name='instance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 21, 54, 49, 534645)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 21, 54, 49, 536651)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 21, 54, 49, 533648)),
        ),
        migrations.AddField(
            model_name='ally',
            name='playable_class',
            field=models.ManyToManyField(blank='True', help_text='Enter a class for this character or leave blank if it is not known', to='dnd_codex.playableclass'),
        ),
        migrations.AddField(
            model_name='creature',
            name='playable_class',
            field=models.ManyToManyField(blank='True', help_text='Enter a class for this character or leave blank if it is not known', to='dnd_codex.playableclass'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='playable_class',
            field=models.ManyToManyField(blank='True', help_text='Enter a class for this character or leave blank if it is not known', to='dnd_codex.playableclass'),
        ),
    ]
