# Generated by Django 4.2.1 on 2023-06-15 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0017_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ally',
            old_name='playable_class',
            new_name='playableclass',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='playable_class',
            new_name='playableclass',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='playable_class',
            new_name='playableclass',
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 21, 58, 19, 369633)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 21, 58, 19, 371667)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 21, 58, 19, 367668)),
        ),
    ]
