# Generated by Django 4.2.1 on 2023-06-15 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0020_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='instance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='instance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 10, 3, 120218)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 10, 3, 122217)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 10, 3, 119219)),
        ),
    ]
