# Generated by Django 4.2.1 on 2023-06-15 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0021_characterclass_instance_count_race_instance_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='instance_count',
        ),
        migrations.RemoveField(
            model_name='damagetype',
            name='instance_count',
        ),
        migrations.RemoveField(
            model_name='race',
            name='instance_count',
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 26, 39, 19659)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 26, 39, 21659)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 26, 39, 18659)),
        ),
    ]
