# Generated by Django 4.2.1 on 2023-06-15 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0022_remove_characterclass_instance_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ally',
            options={'verbose_name_plural': 'Enemies'},
        ),
        migrations.AlterModelOptions(
            name='creature',
            options={'verbose_name_plural': 'Enemies'},
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name_plural': 'Enemies'},
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 35, 26, 574588)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 35, 26, 576587)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 14, 22, 35, 26, 572588)),
        ),
    ]
