# Generated by Django 4.2.1 on 2023-06-16 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0025_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterClass',
            new_name='PlayableClass',
        ),
        migrations.RenameField(
            model_name='ally',
            old_name='characterClass',
            new_name='playableClass',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='characterClass',
            new_name='playableClass',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='characterClass',
            new_name='playableClass',
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 9, 3, 891908)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 9, 3, 893908)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 9, 3, 890909)),
        ),
    ]
