# Generated by Django 4.2.1 on 2023-06-16 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0026_rename_characterclass_playableclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 18, 48, 815721)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 18, 48, 816721)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 18, 48, 813721)),
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a subclass ', max_length=50)),
                ('parentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='dnd_codex.playableclass')),
            ],
        ),
    ]
