# Generated by Django 4.2.1 on 2023-06-16 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0028_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(help_text='Enter a color code for this event type', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 35, 21, 79385)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 35, 21, 81387)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 35, 21, 78386)),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('events', models.TextField()),
                ('allies', models.ManyToManyField(blank=True, to='dnd_codex.ally')),
                ('enemies', models.ManyToManyField(blank=True, to='dnd_codex.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_codex.eventtype')),
            ],
        ),
    ]
