# Generated by Django 4.2.1 on 2023-06-16 00:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0029_eventtype_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='journal_entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dnd_codex.journalentry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 50, 41, 397060)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 50, 41, 399027)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 50, 41, 396057)),
        ),
    ]
