# Generated by Django 4.2.1 on 2023-06-16 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0031_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='journal_entry',
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 56, 57, 634695)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 56, 57, 636694)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 15, 19, 56, 57, 633694)),
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='events',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='events',
            field=models.ManyToManyField(to='dnd_codex.event'),
        ),
    ]
