# Generated by Django 4.2.1 on 2023-06-17 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0032_remove_event_journal_entry_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='playableclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 22, 17, 42, 431568)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 22, 17, 42, 433950)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 22, 17, 42, 426235)),
        ),
    ]
