# Generated by Django 4.2.1 on 2023-06-25 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_codex', '0037_alter_ally_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='damageType',
            field=models.ManyToManyField(help_text='Select a damage type from previous types or create a new one using the + button\n', null=True, to='dnd_codex.damagetype'),
        ),
        migrations.AlterField(
            model_name='ally',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=datetime.datetime(2023, 6, 24, 19, 45, 3, 105406)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='damageType',
            field=models.ManyToManyField(help_text='Select a damage type from previous types or create a new one using the + button\n', null=True, to='dnd_codex.damagetype'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 24, 19, 45, 3, 107406)),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='damageType',
            field=models.ManyToManyField(help_text='Select a damage type from previous types or create a new one using the + button\n', null=True, to='dnd_codex.damagetype'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 24, 19, 45, 3, 104406)),
        ),
    ]
